# Cloud Build pipeline for the Next.js frontend application.

timeout: 1800s
options:
  machineType: E2_HIGHCPU_8

substitutions:
  _REGION: asia-northeast3
  _REPOSITORY: coin-sangjang-frontend
  _SERVICE: frontend
  _PROMOTE_TAG: latest
  _TURBO_FILTERS: frontend...

steps:
  - id: verify-frontend-sources
    name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - '--file=infrastructure/cloud-build/Dockerfile.ci'
      - '--target=ci'
      - '--build-arg=TURBO_FILTERS=$_TURBO_FILTERS'
      - '--tag=ci-frontend'
      - '--progress=plain'
      - .

  - id: build-frontend-image
    name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - '--file=infrastructure/docker/Dockerfile.frontend'
      - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$COMMIT_SHA'
      - '--progress=plain'
      - .

  - id: tag-frontend-release
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$COMMIT_SHA'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$_PROMOTE_TAG'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$COMMIT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$_PROMOTE_TAG'
